# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#Users seed

User.destroy_all

admin = User.create!(email: 'admin@example.com',
                     name: 'Admin',
                     password: '12345678',
                     password_confirmation: '12345678'
)

admin.add_role :admin

customer = User.create!(email: 'customer@example.com',
                        name: 'Customer',
                        password: '12345678',
                        password_confirmation: '12345678'
)
customer.purchases << Purchase.new(state: 'open')
customer.save!
customer.add_role :customer

#Publisher seed

Publisher.destroy_all

publishers = Publisher.create!([{name: 'Amazon'}, {name: 'Móra'},{name: 'Agave'}, {name: 'Piros'}])

#Author seed

Author.destroy_all

authors = Author.create!([{name: 'George R.R. Martin'}, {name: 'H.P. Lovecraft'}, {name: 'Arthur Conan Doyle'}, {name: 'Jamie Oliver'},
                          {name: 'J.K. Rowling'}, {name: 'Darren Shan'}, {name: 'Christopher Moore'}, {name: 'Cassandra Clare'},])

#Genres seed

Genre.destroy_all

genres = Genre.create!([{name: 'Fantasy'},
                        {name: 'Mystery'},
                        {name: 'Sci-fi'},
                        {name: 'Horror'},
                        {name: 'Business'},
                        {name: 'Classics'},
                        {name: 'Manga'},
                        {name: 'Poetry'},
                        {name: 'Cookbooks'},
                        {name: 'Romance'},
                        {name: 'Thriller'},
                        {name: 'History'},
                        {name: 'Fiction'},
                        {name: 'Crime'},
                        {name: 'Children\'s'},
                        {name: 'Comics'},
                        {name: 'Novels'}])

#Stores seed

Store.destroy_all
BookStore.destroy_all

stores = Store.create!([{name: 'Szegedi Könyvesbolt', address: '6734 Szeged, Pál utca 4.'},
                        {name: 'Pesti Könyvesbolt', address: '1334 Budapest, Szent István tér 3.'},
                        {name: 'Debreceni Könyvesbolt', address: '4225 Debrecen, Petőfi sándor utca 27.'},
                        {name: 'Kecskeméti Könyvesbolt', address: '6000 Kecskemét, Kiss Árpád tér 12.'},
                        {name: 'Pécsi Könyvesbolt', address: '7622 Pécs, Kossuth Lajos utca 76.'},
                        {name: 'Miskolci Könyvesbolt', address: '3530 Miskolc, Váci utca 1.'},])

#Books seed

Book.destroy_all

books = Book.create!([{title: 'A Dance with Dragons',
                       author: Author.find_by(name: 'George R.R. Martin'),
                       publisher: Publisher.find_by(name: 'Amazon'),
                       price: 4990,
                       published_date: Date.new(2011,01,01),
                       page_count: 1125,
                       genres: Genre.where(name: ['Fantasy', 'Fiction']),
                       description: 'In the aftermath of a colossal battle, the future of the Seven Kingdoms hangs in the balance — beset by newly emerging threats from every direction. In the east, Daenerys Targaryen, the last scion of House Targaryen, rules with her three dragons as queen of a city built on dust and death.
                        But Daenerys has thousands of enemies, and many have set out to find her. As they gather, one young man embarks upon his own quest for the queen,
                        with an entirely different goal in mind.'},
                      {title: 'Contváros',
                       author: Author.find_by(name: 'Cassandra Clare'),
                       publisher: Publisher.find_by(name: 'Piros'),
                       price: 4000,
                       published_date: Date.new(2014,01,01),
                       page_count: 470,
                       genres: Genre.where(name: ['Fantasy']),
                       description: 'Amikor a tizenöt éves Clary Fray elindul a Pandemonium nevű New York-i klubba, aligha számít rá, hogy egy gyilkosság tanúja lesz – amit ráadásul három, különös tetoválásokkal borított és bizarr fegyverekkel hadonászó tinédzser követ el. A holttest aztán eltűnik a semmiben. Nehéz kihívni a rendőrséget, ha a gyilkosok mindenki más számára láthatatlanok, és semmi – még egy vércsepp sem – bizonyítja, hogy egy fiú meghalt. De fiú volt-e az áldozat egyáltalán? Így találkozik Clary először az Árnyvadászokkal, akik azért küzdenek, hogy megszabadítsák a földet a démonoktól. Közülük való az angyali külseje ellenére igazi bunkó módjára viselkedő Jace is. Clary egyetlen nappal később, akarata ellenére már bele is csöppen Jace világába: édesanyja eltűnik, őt magát pedig megtámadja egy démon. De miért érdekelne egy démont két olyan hétköznapi mondi, mint Clary és az édesanyja? És hogyan tett szert Clary egyszer csak a Látásra? Az Árnyvadászok tudni szeretnék..'},
                      {title: 'Hamuváros',
                       author: Author.find_by(name: 'Cassandra Clare'),
                       publisher: Publisher.find_by(name: 'Piros'),
                       price: 4000,
                       published_date: Date.new(2013,01,01),
                       page_count: 416,
                       genres: Genre.where(name: ['Fantasy']),
                       description: 'Clary Fray másra sem vágyik, csak hogy végre ismét normális életet élhessen. De vajon mi számít normálisnak, ha valaki démonokat pusztító Árnyvadász, az édesanyja varázslattal előidézett kómában fekszik, és egyszerre vérfarkasok, vámpírok meg tündérek nyüzsögnek körülötte? Clary szívesen töltene több időt legjobb barátjával, Simonnal, csakhogy az Árnyvadászoktól nem szabadulhat - főleg nem jóképű, ámde bosszantó, újonnan megtalált bátyjától, Jace-től. Clary csakis úgy segíthet édesanyján, ha felkutatja a rossz útra tért Árnyvadászt, Valentine-t, aki talán őrült, bizonyosan gonosz - ráadásul az édesapja. Amikor a Végzet Ereklyéi közül a másodikat is ellopják, a félelmetes Inkvizítor Jace-t gyanúsítja. Lehet, hogy a fiú tényleg elárul mindent, amiben hitt, és az apja mellé áll?'},
                      {title: 'Üvegváros',
                       author: Author.find_by(name: 'Cassandra Clare'),
                       publisher: Publisher.find_by(name: 'Piros'),
                       price: 4000,
                       published_date: Date.new(2014,01,01),
                       page_count: 500,
                       genres: Genre.where(name: ['Fantasy']),
                       description: 'Hogy megmentse édesanyja életét, Clarynek el kell utaznia az Üvegvárosba, az Árnyvadászok ősi otthonába még ha engedély nélkül belépni a városba a Törvénybe is ütközik, márpedig a Törvény megszegése halált jelenthet. Ha ennyi nem lenne elég, Jace nem akarja, hogy ott legyen, Simont pedig börtönbe vetették az Árnyvadászok, akik igencsak gyanúsnak találnak egy vámpírt, akinek nem árt a napfény. Ahogy Clary egyre többet tud meg családja múltjáról, szövetségesre lel Sebastian, a titokzatos Árnyvadász személyében. Valentine minden erejével azon van, hogy örökre megsemmisítsen minden Árnyvadászt, nekik pedig csak akkor van esélyük vele szemben, ha összefognak örökös ellenségeikkel. De félre tudják-e tenni gyűlöletüket az Árnyvadászok és az Alvilágiak, hogy együttműködhessenek? Miközben Jace rádöbben, mi mindent hajlandó kockára tenni Claryért, vajon a lány újonnan meglelt képességeivel segíthet-e megmenteni az Üvegvárost bármilyen áron? A szerelem halálos bűn, és a múlt titkai is végzetesnek bizonyulnak, amikor Clary és Jace szembenéz Valentine-nal a New York Times nagysikerű sorozatának, A Végzet Ereklyéinek utolsó darabjában.'},
                      {title: 'Biff evangéliuma',
                       author: Author.find_by(name: 'Christopher Moore'),
                       publisher: Publisher.find_by(name: 'Agave'),
                       price: 3000,
                       published_date: Date.new(2013,01,01),
                       page_count: 440,
                       genres: Genre.where(name: ['Comics']),
                       description: 'Jézus születésének történetét jól ismerjük. Csakúgy, mint bölcs tanításait, dicső cselekedeteit és önfeláldozását. De Isten Fiának gyermekkoráról és felnőtté válásának részleteiről senki nem tud semmit - Biffet, a Messiás legjobb haverját kivéve, akit most feltámaszt egy Raziel nevű botcsinálta angyal, hogy írja meg a saját evangéliumát. Úgyhogy Biff egy szállodai szobába zárva nekiáll elmesélni az elveszettnek hitt évek történetét. Senkit és semmit nem kímélve végre kipakol a maga sajátos stílusában (nem véletlenül törölték ki őt az evangéliumokból), és megosztja velünk, hogy hogyan is történt minden valójában. Biff evangéliuma tele van izgalmas kalandokkal, szerelemmel, varázslattal, gyógyítással, halottkeltéssel, démonokkal és dögös csajokkal. De történjen bármi, egyet biztosra vehetünk: Biffet nem olyan fából faragták, hogy csak úgy szó nélkül hagyja a legjobb barátját keresztre feszíteni. Nem. Ő harcolni fog a végsőkig.'},
                      {title: 'Vérszívó démonok',
                       author: Author.find_by(name: 'Christopher Moore'),
                       publisher: Publisher.find_by(name: 'Agave'),
                       price: 3000,
                       published_date: Date.new(2008,01,01),
                       page_count: 266,
                       genres: Genre.where(name: ['Comics']),
                       description: 'Jody igazából nem akart vámpír lenni. De amikor egyszer egy sikátorban ébred - karján égési sérülések, testén egy szemetes konténer, végtagjaiban természetfeletti erő, torkában valami furcsa szomjúság -, rá kell döbbennie, hogy ebben a kérdésben senki nem kérte ki a véleményét. Valaki vámpírt csinált belőle, és kész. Egy vámpír élete azonban sokkal bonyolultabb, mint egy irodai alkalmazotté. Az éjszaka számtalan kihívást rejteget Jody számára, és itt jön a képbe C. Thomas Flood, aki éppen most érkezik San Franciscóba, azzal a feltett szándékkal, hogy író legyen. De a körülmények egészen más irányba sodorják a fiút. Éjszakai munkát vállal egy szupermarketben, és amikor a sors egy gyönyörű, bár élőhalott és vérszívó lány karjaiba löki, ő menthetetlenül beleszeret. Jody és Tommy összeköltözik, de az élet csupa veszély, ha az ember egy vámpírral él együtt. Bizonyos esetekben jól jöhet egy füzér fokhagyma, egy közepes méretű feszület... vagy végső esetben egy kihegyezett karó.'},
                      {title: 'Totál szívás',
                       author: Author.find_by(name: 'Christopher Moore'),
                       publisher: Publisher.find_by(name: 'Agave'),
                       price: 3000,
                       published_date: Date.new(2009,01,01),
                       page_count: 222,
                       genres: Genre.where(name: ['Comics']),
                       description: 'Vámpírnak lenni totál szívás. Szó szerint. Kérdezzük csak meg Thomas C. Floodot. Élete legfantasztikusabb éjszakája után arra ébredt, hogy a barátnője, Jody, vámpír. És most már ő is az! Pontosabban Jody tette azzá. A legtöbb párnak ez elég lenne a szakításhoz, de Tommy és Jody szerelmesek, így elhatározzák, hogy túlteszik magukat ezen az apróságon. Csak közben kiderül, hogy az ősöreg vámpírnak, aki korábban megcsócsálta Jodyt, nem lett volna szabad újoncokat toborozni. Ráadásul Tommy volt munkatársai nagyon rákaptak erre a vámpírvadász dologra, úgyhogy karót akarnak döfni a fiú szívébe. Vagy levágni a fejét. Vagy valami ilyesmi. És ez már tényleg totál szívás.'},
                      {title: 'Csak egy harapás',
                       author: Author.find_by(name: 'Christopher Moore'),
                       publisher: Publisher.find_by(name: 'Agave'),
                       price: 3000,
                       published_date: Date.new(2010,01,01),
                       page_count: 270,
                       genres: Genre.where(name: ['Comics']),
                       description: 'Vannak szerelmesek, akik azért születnek, hogy átöleljék egymást. Jody és Tommy azért született, hogy megharapják egymást. Azért születtek újra. Merthogy már vámpírok. Óriási szerencse, hogy a szerelmük így halhatatlan, mivel kegyencük, Abby bronzszoborba öntötte őket a Totál szívás végén. Abby továbbra is vérszívó démon szeretne lenni, csak túl sok a dolga: kerülni a sulit, betörni az új Dög Martens csizmáját és lesmárolni imádott pasiját. Csakhogy ott van Chet, a borotvált macska, aki újdonsült vámpírmacskaként egyre nagyobb és vérszomjasabb. Sőt, az őt követő vámpírmacskák falkája is egyre nagyobb és vérszomjasabb. Van, aki szív. És van, akit szívnak. Christopher Moore őrült vámpírtrilógiájának befejező darabjában senki sincs biztonságban'},
                      {title: 'A rémségek cirkusza',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2006,02,10),
                       page_count: 300,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'A regénysorozat első kötetében Darren és Steve, a két barát ellátogat a titokzatos cirkuszba, amely az ódon kastély szomszédságában ütötte fel a táborát. A városban persze senki sem értesült a társulatról, és a mi a legfontosabb: a szülők és a tanárok sem tudnak róla. Mág a szórólapokat is titokban terjesztik a kék csuljások! Itt ugyanis nem akrobaták és oroszlánok szórakoztatják a közönséget. Nincsenek bohócok, sem idomított elefántok... valóságos rémségek riogatják a nézőt.A legszörnyűbb dolog azonban az előadás után következik. Steve felismeri az egyik szereplőt... látott róla egy rajzot valami régi könyvben, és ebből megtudta, hogy az illető vámpír...„Lenyűgöző könyv... fordulatokban gazdag meséje felkelti az olvasó kíváncsiságát a folytatásra.” - J. K. Rowling, a Harry Potter könyvek szerzője.'},
                      {title: 'A vámpír inasa',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2007,01,01),
                       page_count: 300,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: '"Félvámpír vagyok - jelenti ki a kötet elején Darren Shan. - Egészen addig ember voltam, amíg nem találkoztam az éjszaka teremtményével. Ettől fogva örökre megváltozott az életem. Mr. Crepsley arra kényszerített , hogy legyek az inasa, így elszegődtem a Rémségek Cirkuszához. Nehezen tanultam bele új életebe. Még ennél is nehezebben ment a vérszívás, sokáig nem is voltam hajlandó rá. Végül ráfanyalodtam, hogy megőrizzem egy haldokló barátom emlékeit (a vámpírok képesek elraktározni egy ember emlékeit, ha az utolsó cseppig kiszívják a vérét). Hetekig rettenetes lidércnyomások gyötörtek, de nem volt visszatérés. Elfogadtam vámpírinas mivoltomat, és megtanultam élni a benne rejlő lehetőségekkel... idővel valódi éjszakai lénnyé váltam..."'},
                      {title: 'A vérszipoly',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2007,07,01),
                       page_count: 300,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'Másfél év telt el azóta, hogy a vámpír társaságában elhagytam az otthonomat - folytatja a történetet Darren Shan. - Erősebb vagyok, mint bármelyik korombeli fiú, gyorsabban is futok, messzebbre tudok ugrani, és éles körmeimmel a téglafalat is ki tudom vájni. A hallásom, a látásom és a szaglásom rendkívüli módon kiélesedett...Szükségem is volt e mágikus képességekre, miután a városkában, ahol a közönséget ijesztgettük, megjelent a gonosz és gyilkos Mr. Murlough, a mindenre elszánt könyörtelen vérszipoly..'},
                      {title: 'A vámpírok hegye',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2010,01,01),
                       page_count: 300,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'Darren Shan és Mr. Crepsley veszedelmes útra indulnak, egyenesen a vámpírvilág szívébe. De nemcsak a havas-jeges Vámpírok Hegyével kell megküzdeniük - az úton megelőzték őket a vérszipolyok... Mi történik Darrennel, ha bemutatják a Vezérkarnak és a hercegeknek? Helyreáll-e embersége, avagy örökre beszippantja őt a sötétség? Egyvalami biztos: sohasem hitte volna, hogy ennyi halálos veszedelmet rejt a szertartás, mellyel befogadják a vámpírok klánjába.'},
                      {title: 'A halál próbái',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2009,01,01),
                       page_count: 300,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'A vámpírok hegyének dermesztő folytatása: A Próbák: a halál tizenhét neme, hacsak nem vesz pártfogásába a vámpírok szerencséje. Darren Shannak öt félelmetes próbát kell kiállnia, hogy bizonyítson a vámpírok klánja előtt vagy útja egyenesen a Halál Termébe vezet. De a Vámpírok Hegye titkos veszedelmeket rejt. Baljós erők gyülekeznek a sötétség leple alatt. A vérontás és árulás e lidérces honában még a halál is megváltás lehet...A hatodik könyvben, a Vámpír hercegben elkövetkezik a döbbenetes leszámolás pillanata.'},
                      {title: 'A vámpírherceg',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2011,01,01),
                       page_count: 300,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'Az árulónak bélyegzett Darren Shan farakasszemet néz a halállal. Hiába szökött meg, a vér szava visszahívja. A Vámpírok Hegyén ugyanis véres lesszámolásra készülnek a hatalomra éhes vérszipolyok. Vajon kis lesz az éjszaka ura?Tud-e fordítani Darern Shan az események menetén, vagy eljött a vámpírok több ezer éves uralmának vége?A Vámpírok Hegye trilógia ezzel lezárul - a történetnek azonban még nincs mége!Jön a A sötétség vadászaiDarren Shan 1972-ben született Londonban. Mindössze hatéves volt, amikor a család az írországi Limerickbe költözött. Középiskoláit a szomszédos Askeatonban végezte, ahol édesanyja is tanított. Gyerekkori olvasmányait a Drakula-történetek és az ír-kelta mondavilág határozta meg. Alig tizenöt éves, és megírja első regényét! Egyetemista korára már megízleli a sikert, amikor is egy pályázatra benyújtott művével első díjat nyer. A Rémségek Cirkusza az első gyerekkönyve, amely hihetetten sikert hozott a fiatal szerzőnek: máris Stephen King és Tolkien utódjaként emlegetik. A vámpírtörténet Amerikát is meghódította ráadásul a Wagner Bros szerződést kötött a megfilmesítésére'},
                      {title: 'A sötétség vadászai',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2008,01,01),
                       page_count: 206,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'Darren Shanra, a Hercegre gyilkos küldetés vár: néhány társával meg kell találnia a Vérszipolyok Urát, aki komolyan veszélyezteti a klánt. A feladat korántsem egyszerű: a jóslatok szerint eleve kudarcra vannak ítélve, hiszen ellenfelük nehezen ismerhető fel, ráadásul számos segítője van. Vajon bízhatnak-e Darrenék a bűbájos-rettenetes boszorkányban, Lady Evannában, aki minden titok tudója? Mindenesetre úgy tűnik, egyedül ő segíthet. Azonban alighogy kezdetét veszi az őrült hajsza, a Herceg és alakulata vérszipolyokba botlik... A szerzőről: 1972-ben született Londonban.Mindössze hatéves volt, amikor a család az írországi Limerickbe költözött. Középiskoláit a szomszédos Askeatonban végezte, ahol édesanyja is tanított. Gyerekkori olvasmányait az ír-kelta mondavilág és a Drakula-történetek határozták meg. Alig tizenöt éves, és megírja első regényét! Egyetemista korára már megízleli a sikert, amikor is egy pályázatra benyújtott művévél első díjat nyer. A Rémségek Cirkusza az első gyerekkönyve, amely hihetetlen sikert hozott a fiatal szerzőnek: máris Stephen King és Tolkien utódjaként emlegetik. A vámpírtörténet Amerikát is meghódította, ráadásul a Warner Bros szerződést kötött a megfilmesítésére.'},
                      {title: 'Az éjszaka szövetségesei',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2014,01,01),
                       page_count: 222,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'Folytatódik a hajsza a Vérszipolyok Ura után. Shan herceg, Mr. Crepsley és Harkat, úgy tűnik csapdába került: nem elég, hogy felfedezték lakhelyüket, valaki gonosz tréfát űz velük. Ki lehet a titokzatos Kampós? Van-e köze az éjszaka teremtményeihez? Egy biztos: bármerre mennek is, a vámpírok mindenütt holttestekbe botlanak. De ki a tettes?'},
                      {title: 'A hajnal gyilkosai',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2008,01,01),
                       page_count: 206,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'Túljártak a vadászok eszén, s most számban megfogyatkozva menekülnek. Nyomukban a vérszipolyok, a felizgatott csőcselék és a rendőrség. Az egyes számú közellenség Darren Shan, a Vámpír Herceg. A vámpírok összecsapásra készülnek vérszomjas ellenségeikkel. Életre-halálra. Ez lesz a vég Darren és szövetségesei számára? A Megtorlás Barlangjában minden kiderül... Ha túlélted a hajnalt, utazz el oda, ahol a történet folytatódik.'},
                      {title: 'A lelkek tava',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2009,01,01),
                       page_count: 238,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'A Sebhelyesek Háborúja újabb fordulóponthoz érkezik, előbb azonban a Sors, vagyis Mr.Tiny veszélyes útra küldi a Vámpír Herceget és Harkatot, a törpe személyt: fel kell keresniük a Lelkek Tavát, az élveholtak birodalmát. Utazás térben és időben a borzalmak földjén... az egyedüli segítségük Lady Evanna, a boszorkány. Vagy mégsem? A groteszk...'},
                      {title: 'Az árnyak ura',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2009,01,01),
                       page_count: 216,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'Mostantól itt minden az Árnyak Urának tartozik engelmességgel-mondta Steve halkan. Ez itt már az én világom...Darren Shan hazamegy. A világ amely valaha az övé volt pokollá válik. Régi ellenségei várnak rá. Sorsdöntő lépéseket kell tennie. Bizonyosnak látszik, hogy sorsa a pusztulás,a világ fölött átveszi az uralmat az Éjszaka Fejedelme......'},
                      {title: 'A végzet fiai',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2009,01,01),
                       page_count: 230,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'A Sebhelyesek Háborújának megdöbbentő befejezése…. A népszerű Vámpír sorozat utolsó, befejező kötetét veheti kézbe az olvasó.'},
                      {title: 'Démonmester',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2010,01,01),
                       page_count: 250,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'Amikor Grubbs Grady először áll szemtől szembe Vész herceggel és förtelmes csatlósaival, három dolgot tanul meg: a világ gonosz, a varázslat lehetséges, démonok léteznek. Úgy gondolja, soha többé nem lesz részese ilyen iszonytató eseményeknek, mint ezen a koromsötét, halálszagú éjszakán. Nagyot téved. Darren Shan, a nagy sikerű Vámpír Könyvek szerzője új sorozatában a Démonvilág borzalmait ecseteli nagy átéléssel. Az első kötet tizenhárom éves főhősének arra a kérdésre kell megtalálnia a választ: mi a jobb: farkasemberré válni, vagy szembeszállni a nagy hatalmú démonmesterrel.'},
                      {title: 'Démontolvaj',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2008,01,01),
                       page_count: 268,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'Amikor Kernel Fleck öccsét elrabolják a démonok, kénytelen utánamenni, hogy megkeresse. A Démonvilág minden képzeletet felülmúló veszélyekkel teli univerzumában, ahol a káosz uralkodik, varázserő nélkül esély sincs a túlélésre.'},
                      {title: 'Vérfüred',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2008,01,01),
                       page_count: 252,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'Ne higgy a meséknek! Vidám befejezés nem létezik. Sőt. Befejezés sincs. Az élet megy tovább, két kanyarral arrébb már mindig történik valami új. Legyőzhetsz hatalmas akadályokat, dacolhatsz ezer veszéllyel, farkasszemet nézhetsz a gonosszal, a végén dicsekedhetsz is vele, de az még nem a befejezés. Amíg van benned szufla, a történeted pereg tovább.

									Dervish Gradyt lidérces álmok kínozzák, amióta visszatért a Démonvilág univerzumából, de Grubbs nagyon vigyáz nagybátyjára. Megpróbálnak normális, démonmentes életet élni. Amikor aztán egy híres producer felkéri Dervisht, hogy vegyen részt következő horrorfilmje elkészítésében szakértőként, úgy gondolják, ez jó buli lehet, és amúgy sem árta-na nekik egy kis levegőváltozás.

									Csakhogy a forgatás helyszínén, a Vérfüred névre keresztelt városkában, nem csupán feltörő emlékeikkel kell megküzdeniük.'},
                      {title: 'Áldozat',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2007,01,01),
                       page_count: 265,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'Már majdnem kiérek a szabadba, amikor hátborzongató suttogás hangzik fel a hátam mögött. "Apróóósááág.." Megfordulok. Ne látok semmit, de tudom, hogy nem vagyok egyedül. Segítségért kiáltanék, de képtelen vagyok rá. Aztán karmok csapnak elő a sötétből.. eltorzult arc.. tűzben égő szempár.. vicsorgón, durva állkapocs.. a démon rám veti magát. 
									Csecsemőként Bec az életéért küzdött. Mialatt papnőnek tanul, azért küzd, hogy fogadja be a klán, amelynek szüksége van az aprócska lány kivételes képességeire, mégis fél a benne lakozó varázserőtől. És amikor feltűnnek a démonok, az efféle küzdelmek helyét véres harc veszi át. 
									Bec varázsereje gyenge, de aztán sorsa összehozza egy druidával, aki felfedi előtte a csillagok mágiájának titkait. Drust vezetésével a lány és néhány bátor harcos hosszú, veszélyekkel teli útra indul, hogy visszaűzze a förtelmes rémalakokat a saját világukba. 
									A maroknyi csapat emberfeletti erővel harcol, bármilyen áldozatot kész meghozni, hogy megmentse népét a végső pusztulástól. Ám azt még a druida sem látja előre, milyen iszonya szenvedés az ára annak, ha egy ember szembeszáll a nagy hatalmú démonmesterrel..'},
                      {title: 'Fenevad',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2007,01,01),
                       page_count: 248,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'Grubbs Gradyn mostanáig nem fogott a családi átok, ám egyszerre furcsa és riasztó tüneteket észlel magán teliholdkor. Úgy érzi, közel a rettegett vég, és csak hajszálnyi választja el attól, hogy testét-lelkét elnyelje a feneketlen sötétség. Kicselezte a halált, dacolt a démonokkal, és harcolt a túlélésért, most viszont a varázserő birokra kel a benne rejlő szörnyeteggel. Vajon sikerül-e megfékeznie a fenevadat, vagy őt is maga alá gyűri az átok és vérfarkassá változik?'},
                      {title: 'Végítélet',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2008,01,01),
                       page_count: 230,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'Tűz! Körbevesz és éget, vad vörös lángok csapkodnak felém mindenfelöl. Máris megperzselődött a karomon a szőr, és tudom, hogy pár pillanat múlva meggyullad mindenem. Elönt a pánik... Semmi mást nem látok, csak a lángokat... Rettenetes üvöltés hallatszik, átható, fülhasogató hang. A dobhártyám berepedne, a szemem pedig kipukkadna, ha nem védeném magamat ösztönösen a varázserőmmel. - Ez kész pokol! - nyögöm. Grubbs Gradyre élete legborzalmasabb kalandja vár. Alig szabadult meg a vérszomjas Vész herceg karmai közül, máris kiderül, hogy a kicselezett démonmester ismét bosszúra készül. Ám ezúttal nem egyedül Grubbs életére tör, és nem is csak a családját veszi célba - a tét az egész emberiség életben maradása. Ha Vész hercegnek förtelmes démonjai élén sikerül betörni világunkba, akkor elszabadul a pokol, és óhatatlanul bekövetkezik a végítélet. Vagy mégsem?'},
                      {title: 'Árny',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2008,01,01),
                       page_count: 220,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'Eljött a világégés és a végítélet. Ám a világ mégsem ért véget. A pusztításból új élet keletkezett. Bee visszatért az évszázados fogságból, hogy ismét felvegye a harcot a Démonvilággal. Varázs-hatalma erősebb, mint valaha, de a démonok mellett is feltűnik egy újabb sötét pusztító erő. Már nem Vész herceg az emberiség legfenyegetőbb ellensége...'},
                      {title: 'Farkassziget',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2009,01,01),
                       page_count: 218,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: '"A fák koronája felett elsuhanva meglátjuk a vérfarkasokat. Mutáns, gonosz, szőrös teremtmények, hatalmas muszklikkal, agyarakkal és karmokkal. A bennem lakozó fenevad megpróbál felszínre törni, némán vonít torz testvéreinek. Nem sikerült megszabadulnom a farkastól... Mialatt a titokzatos Árny démonokat toboroz hadseregébe, Grubbs és csapata elkeseredetten igyekszik kideríteni, mivel is áll szemben. Ám amikor egy új nyomot kezdenek követni, legnagyobb meglepetésükre egy régi ellenséghez jutnak el - a Bárányokhoz. A Grady-átok veszélyesebb, mint valaha. A vérfarkasok szabadon portyáznak, és nagyon éhesek..."'},
                      {title: 'Suttogás',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2009,01,01),
                       page_count: 214,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'Tudom, ez röhejes. A fény nem tud suttogni. Mégis, akár meg is esküszöm rá, hogy hallottam, amint egy hang engem szólít. Először csak valami fura sistergés hallatszott, de aztán kitisztult, és egy szót ismételgetett újra meg újra. És a fények azt az egy szót suttogják azóta is halkan, titokzatosan, csábítóan.'},
                      {title: 'A pokol hősei',
                       author: Author.find_by(name: 'Darren Shan'),
                       publisher: Publisher.find_by(name: 'Móra'),
                       price: 2500,
                       published_date: Date.new(2010,01,01),
                       page_count: 226,
                       genres: Genre.where(name: ['Fantasy', 'Fiction', 'Horror']),
                       description: 'A kislány fura tekintettel mered rám. Fiatalabb, mint amilyennek először hittem, a kezében egy játékmackót szorongat. Te vagy a mumus? - suttogja elkerekedő szemmel. Igen - felelem rekedten, aztán megragadom a fejét hatalmas, sebhelyes, véráztatta karommal, és összeroppantom. Beranabus és Dervish halott. Bec szentségtelen szövetségre lépett Vész herceggel. Kernel megvakult, és akarata ellenére a Földön tartják. Grubbs szinte beleőrül a bánatba, és kezdi elveszíteni az önuralmát. A démonok átkelnek. A Tanítványok hullanak.'},
                      {title: 'The Call of Cthulhu',
                       author: Author.find_by(name: 'H.P. Lovecraft'),
                       publisher: Publisher.find_by(name: 'Amazon'),
                       price: 2990,
                       published_date: Date.new(1926),
                       page_count: 43,
                       genres: Genre.where(name: ['Fantasy', 'Horror', 'Classics', 'Novels']),
                       description: 'One of the feature stories of the Cthulhu Mythos, H.P. Lovecraft’s “The Call of Cthulhu” is a harrowing tale
                         of the weakness of the human mind when confronted by powers and intelligences from beyond our world.'},
                      {title: 'The Complete Sherlock Holmes',
                       author: Author.find_by(name: 'Arthur Conan Doyle'),
                       publisher: Publisher.find_by(name: 'Amazon'),
                       price: 6990,
                       published_date: Date.new(1986,10,01),
                       page_count: 1796,
                       genres: Genre.where(name: ['Mystery', 'Crime', 'Classics']),
                       description: 'London Edwardian private detective Sherlock Holmes. Four novels, 5 books of 56 short stories.
                        1 A Study in Scarlet
                        2 The Sign of the Four
                        3 The Hound of the Baskervilles
                        4 The Valley of Fear

                        1 The Adventures of Sherlock Holmes
                        2 The Memoirs of Sherlock Holmes
                        3 The Return of Sherlock Holmes
                        4 His Last Bow
                        5 The Case-Book of Sherlock Holmes'},
                      {title: 'Cook with Jamie',
                       author: Author.find_by(name: 'Jamie Oliver'),
                       publisher: Publisher.find_by(name: 'Amazon'),
                       price: 5990,
                       published_date: Date.new(2007,06,01),
                       page_count: 437,
                       genres: Genre.where(name: ['Cookbooks']),
                       description: 'This is my guide to making you a better cook and it\'s the biggest book I\'ve ever done!
                       I think it looks beautiful and is full of simple and accessible recipes (160 of them!)
                       that will blow the socks off your family and any guests you might have round for dinner.
                       And that\'s not all ... there\’s information on the equipment that I think you should have in your kitchen,
                       advice on how to recognize and cook loads of different cuts of meat, as well as on how to get the best value
                       and quality when you\’re out shopping.
                       With Britain consuming more processed food than the rest of Europe put together, it\’s a sad fact that most people just aren\’t
                       confident enough to cook any more. I\'m hoping that with this new book, everyone will get stuck in and reclaim our fantastic cooking heritage!'},
                      {title: 'Harry Potter Boxset',
                       author: Author.find_by(name: 'J.K. Rowling'),
                       publisher: Publisher.find_by(name: 'Amazon'),
                       price: 16990,
                       published_date: Date.new(2007,10,16),
                       page_count: 4100,
                       genres: Genre.where(name: ['Children\'s', 'Fantasy', 'Fiction', 'Novels']),
                       description: 'The exciting tales of Harry Potter, the young wizard-in-training, have taken the world by storm,
                       and fans just can\'t get enough of the magical world of Hogwarts and beyond. If you buy one of the Harry Potter books,
                       we guarantee you\'ll want the next...and the next...and the next -- so why not have them all, right at your fingertips? With the Harry Potter Boxed Set (Years 1-7),
                       Barnes & Noble.com offers simple one-stop shopping for your Harry Potter library! As easy as the wave of a magic wand, you can get all seven Harry Potter books delivered to your doorstep at once.
                       The Harry Potter Boxed Set includes hardcover editions of Harry Potter and the Sorcerer\'s Stone, Harry Potter and the Chamber of Secrets, Harry Potter and the Prisoner of Azkaban,
                       Harry Potter and the Goblet of Fire, Harry Potter and the Order of the Phoenix, Harry Potter and the Half-Blood Prince, and Harry Potter and the Deathly Hallows. The books come snugly packed in a decorative,
                       trunk-like box with sturdy handles and a privacy lock -- and includes decorative stickers!'},])

BookStore.create!([{book: Book.find_by(title: 'A Dance with Dragons'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 30},
                   {book: Book.find_by(title: 'The Call of Cthulhu'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 15},
                   {book: Book.find_by(title: 'The Complete Sherlock Holmes'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 42},
                   {book: Book.find_by(title: 'Cook with Jamie'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 10},
                   {book: Book.find_by(title: 'Harry Potter Boxset'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'A rémségek cirkusza'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 5},
                   {book: Book.find_by(title: 'A vámpír inasa'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'A vérszipoly'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 10},
                   {book: Book.find_by(title: 'A vámpírok hegye'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'A Halál próbái'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'A vámpírherceg'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'A sötétség vadászai'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'Az éjszaka szövetségesei'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'A lelkek tava'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'A hajnal gyilkosai'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'Az árnyak ura'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'A végzet fiai'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'Démonmester'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'Démontolvaj'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'Vérfüred'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'Áldozat'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'Fenevad'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'Végítélet'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'Árny'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'Farkassziget'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'Suttogás'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'A pokol hősei'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 13},
                   {book: Book.find_by(title: 'Biff evangéliuma'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 5},
                   {book: Book.find_by(title: 'Vérszívó démonok'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 5},
                   {book: Book.find_by(title: 'Totál szívás'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 5},
                   {book: Book.find_by(title: 'Csak egy harapás'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 5},
                   {book: Book.find_by(title: 'Contváros'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 6},
                   {book: Book.find_by(title: 'Hamuváros'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 6},
                   {book: Book.find_by(title: 'Üvegváros'), store: Store.find_by(name: 'Szegedi Könyvesbolt'), quantity: 6},
                   {book: Book.find_by(title: 'A Dance with Dragons'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'The Call of Cthulhu'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 34},
                   {book: Book.find_by(title: 'The Complete Sherlock Holmes'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 8},
                   {book: Book.find_by(title: 'Cook with Jamie'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 2},
                   {book: Book.find_by(title: 'Harry Potter Boxset'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 5},
                   {book: Book.find_by(title: 'A rémségek cirkusza'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 10},
                   {book: Book.find_by(title: 'A vámpír inasa'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 6},
                   {book: Book.find_by(title: 'A vámpírok hegye'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'A Halál próbái'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'A vámpírherceg'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'A sötétség vadászai'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'Az éjszaka szövetségesei'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'Démonmester'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'Vérfüred'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'Áldozat'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'Contváros'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 2},
                   {book: Book.find_by(title: 'Hamuváros'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 2},
                   {book: Book.find_by(title: 'Üvegváros'), store: Store.find_by(name: 'Pesti Könyvesbolt'), quantity: 2},
                   {book: Book.find_by(title: 'A rémségek cirkusza'), store: Store.find_by(name: 'Debreceni Könyvesbolt'), quantity: 2},
                   {book: Book.find_by(title: 'A vámpír inasa'), store: Store.find_by(name: 'Debreceni Könyvesbolt'), quantity: 7},
                   {book: Book.find_by(title: 'A vérszipoly'), store: Store.find_by(name: 'Debreceni Könyvesbolt'), quantity: 3},
                   {book: Book.find_by(title: 'A vámpírok hegye'), store: Store.find_by(name: 'Debreceni Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'Démontolvaj'), store: Store.find_by(name: 'Debreceni Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'Démonmester'), store: Store.find_by(name: 'Debreceni Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'Contváros'), store: Store.find_by(name: 'Debreceni Könyvesbolt'), quantity: 7},
                   {book: Book.find_by(title: 'Hamuváros'), store: Store.find_by(name: 'Debreceni Könyvesbolt'), quantity: 7},
                   {book: Book.find_by(title: 'Üvegváros'), store: Store.find_by(name: 'Debreceni Könyvesbolt'), quantity: 7},
                   {book: Book.find_by(title: 'A rémségek cirkusza'), store: Store.find_by(name: 'Pécsi Könyvesbolt'), quantity: 3},
                   {book: Book.find_by(title: 'A vérszipoly'), store: Store.find_by(name: 'Pécsi Könyvesbolt'), quantity: 2},
                   {book: Book.find_by(title: 'A vámpírok hegye'), store: Store.find_by(name: 'Pécsi Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'A végzet fiai'), store: Store.find_by(name: 'Pécsi Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'Fenevad'), store: Store.find_by(name: 'Pécsi Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'Végítélet'), store: Store.find_by(name: 'Pécsi Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'Contváros'), store: Store.find_by(name: 'Pécsi Könyvesbolt'), quantity: 2},
                   {book: Book.find_by(title: 'Hamuváros'), store: Store.find_by(name: 'Pécsi Könyvesbolt'), quantity: 2},
                   {book: Book.find_by(title: 'Üvegváros'), store: Store.find_by(name: 'Pécsi Könyvesbolt'), quantity: 2},
                   {book: Book.find_by(title: 'A rémségek cirkusza'), store: Store.find_by(name: 'Miskolci Könyvesbolt'), quantity: 4},
                   {book: Book.find_by(title: 'A vámpír inasa'), store: Store.find_by(name: 'Miskolci Könyvesbolt'), quantity: 6},
                   {book: Book.find_by(title: 'A Halál próbái'), store: Store.find_by(name: 'Miskolci Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'A vámpírherceg'), store: Store.find_by(name: 'Miskolci Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'Démonmester'), store: Store.find_by(name: 'Miskolci Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'Vérfüred'), store: Store.find_by(name: 'Miskolci Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'A rémségek cirkusza'), store: Store.find_by(name: 'Kecskeméti Könyvesbolt'), quantity: 6},
                   {book: Book.find_by(title: 'A vérszipoly'), store: Store.find_by(name: 'Kecskeméti Könyvesbolt'), quantity: 6},
                   {book: Book.find_by(title: 'A vámpírok hegye'), store: Store.find_by(name: 'Kecskeméti Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'A sötétség vadászai'), store: Store.find_by(name: 'Kecskeméti Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'Végítélet'), store: Store.find_by(name: 'Kecskeméti Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'Árny'), store: Store.find_by(name: 'Kecskeméti Könyvesbolt'), quantity: 23},
                   {book: Book.find_by(title: 'Biff evangéliuma'), store: Store.find_by(name: 'Kecskeméti Könyvesbolt'), quantity: 4},
                   {book: Book.find_by(title: 'Vérszívó démonok'), store: Store.find_by(name: 'Kecskeméti Könyvesbolt'), quantity: 4},
                   {book: Book.find_by(title: 'Totál szívás'), store: Store.find_by(name: 'Kecskeméti Könyvesbolt'), quantity: 4},
                   {book: Book.find_by(title: 'Csak egy harapás'), store: Store.find_by(name: 'Kecskeméti Könyvesbolt'), quantity: 4},
                  ])